name: GeneratOre
version: 0.1
description: Ore Generation
author: ame94
main: ca.ame94.generatore.PluginMain

commands:
    genore:
        description: Genratore base command
        permission: generatore.base
        permission-message: ยง4You are not permitted to use this plugin.
        usage: Please use '/genore help' for more info.
